name: reviewdog

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v1
        with:
          github_token: ${{ secrets.github_token }}
          textlint_flags: 'articles/**'
