name: reviewdog

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"

      - name: Cache node modules
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run textlint
        uses: tsuyoshicho/action-textlint@v3.1
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true
          textlint_flags: "articles/**"
