name: reviewdog

on: [pull_request]

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1

      - name: Run lint
        run: yarn textlint:all | reviewdog -reporter=github-pr-check -f=textlint -level="error"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
